main = ".worker-next/index.mjs"
name = "khoj"

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

assets = { directory = ".worker-next/assets", binding = "ASSETS" }
[vars]
NPM_TOKEN = "A+VJwr9/bbnKO5MDhjSYh//F98AvYMRkAFcD/md66RO1yd1RQXGhlHUbnk6Vz64X"
UPLOADTHING_TOKEN='eyJhcGlLZXkiOiJza19saXZlX2I3YWMyOGExNmI0Y2ZlMWQ0MTdhNTJjZmY4MjhmMjg0MjEwOThjMGVmOTkyZDU1Zjc3NTY1MjJjMWE4YTY2NTciLCJhcHBJZCI6ImE2ZzJsbTI2MGsiLCJyZWdpb25zIjpbInNlYTEiXX0='

NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_test_cGxlYXNlZC1kaW5nby0yNS5jbGVyay5hY2NvdW50cy5kZXYk"
CLERK_SECRET_KEY="sk_test_YgmDbYNQbegW8EDvOWQ3Odd4mr4LwMGMjuA96PKsTg"
DATABASE_URL="postgresql://postgres.qzjcxiocsvcdftgnwmxx:CmxKEoLGKaQ4BZBz@aws-0-us-west-1.pooler.supabase.com:6543/postgres"
NODE_ENV="development"

API_URL="http://localhost:8000/"

CLERK_WEBHOOK_SIGNING_SECRET="whsec_zlhjJWZ5G9oKJX43xGQ9bGknukReRUk8"

NEXT_PUBLIC_CLERK_SIGN_IN_URL="/sign-in"
NEXT_PUBLIC_CLERK_SIGN_UP_URL="/sign-up"

DATABASE_USER="postgres.qzjcxiocsvcdftgnwmxx"
DATABASE_PASSWORD="CmxKEoLGKaQ4BZBz"

TRIGGER_SECRET_KEY="tr_dev_vvysuJ4UsK8gzT5WASqC"