main = ".worker-next/index.mjs"
name = "khoj"

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]



assets = { directory = ".worker-next/assets", binding = "ASSETS" }
[vars]
NPM_TOKEN = "A+VJwr9/bbnKO5MDhjSYh//F98AvYMRkAFcD/md66RO1yd1RQXGhlHUbnk6Vz64X"
