###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, List, Optional, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################


class CitationObject(BaseModel):
    in_text: Optional[str] = None
    complete_reference: Optional[str] = None

class NewCitationObject(BaseModel):
    in_text: Optional[str] = None
    complete_reference: Optional[str] = None

class NewPage(BaseModel):
    sections: List["Section"]

class NewSection(BaseModel):
    title: Optional[str] = None
    content: Optional[str] = None
    references: List["CitationObject"]
    is_finished: Optional[bool] = None

class Page(BaseModel):
    sections: List["Section"]

class Paper(BaseModel):
    author: List[Optional[str]]
    title: Optional[str] = None
    year: Optional[str] = None
    abstract: Optional[str] = None

class ReferenceObject(BaseModel):
    text: Optional[str] = None
    url: Optional[str] = None

class References(BaseModel):
    references: List["ReferenceObject"]

class Section(BaseModel):
    title: Optional[str] = None
    content: Optional[str] = None
    references: List["CitationObject"]
    is_finished: Optional[bool] = None
