# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    async def ExtractNewPaperContent(self, previous_section: str,references: str,page_content: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.NewPage:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractNewPaperContent", args={
            "previous_section": previous_section,"references": references,"page_content": page_content,
        })
        return typing.cast(types.NewPage, result.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractPaper(self, paper: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Paper:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractPaper", args={
            "paper": paper,
        })
        return typing.cast(types.Paper, result.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractPaperContent(self, references: str,page_content: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.Page:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractPaperContent", args={
            "references": references,"page_content": page_content,
        })
        return typing.cast(types.Page, result.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractReferences(self, paper: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.References:
        result = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractReferences", args={
            "paper": paper,
        })
        return typing.cast(types.References, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractNewPaperContent(self, previous_section: str,references: str,page_content: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.NewPage, types.NewPage]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractNewPaperContent", args={
            "previous_section": previous_section,"references": references,"page_content": page_content,
        })
        return baml_py.BamlStream[stream_types.NewPage, types.NewPage](
          result,
          lambda x: typing.cast(stream_types.NewPage, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.NewPage, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractPaper(self, paper: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.Paper, types.Paper]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractPaper", args={
            "paper": paper,
        })
        return baml_py.BamlStream[stream_types.Paper, types.Paper](
          result,
          lambda x: typing.cast(stream_types.Paper, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Paper, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractPaperContent(self, references: str,page_content: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.Page, types.Page]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractPaperContent", args={
            "references": references,"page_content": page_content,
        })
        return baml_py.BamlStream[stream_types.Page, types.Page](
          result,
          lambda x: typing.cast(stream_types.Page, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Page, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractReferences(self, paper: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.References, types.References]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractReferences", args={
            "paper": paper,
        })
        return baml_py.BamlStream[stream_types.References, types.References](
          result,
          lambda x: typing.cast(stream_types.References, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.References, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ExtractNewPaperContent(self, previous_section: str,references: str,page_content: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractNewPaperContent", args={
            "previous_section": previous_section,"references": references,"page_content": page_content,
        }, mode="request")
        return result
    async def ExtractPaper(self, paper: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractPaper", args={
            "paper": paper,
        }, mode="request")
        return result
    async def ExtractPaperContent(self, references: str,page_content: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractPaperContent", args={
            "references": references,"page_content": page_content,
        }, mode="request")
        return result
    async def ExtractReferences(self, paper: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractReferences", args={
            "paper": paper,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ExtractNewPaperContent(self, previous_section: str,references: str,page_content: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractNewPaperContent", args={
            "previous_section": previous_section,"references": references,"page_content": page_content,
        }, mode="stream")
        return result
    async def ExtractPaper(self, paper: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractPaper", args={
            "paper": paper,
        }, mode="stream")
        return result
    async def ExtractPaperContent(self, references: str,page_content: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractPaperContent", args={
            "references": references,"page_content": page_content,
        }, mode="stream")
        return result
    async def ExtractReferences(self, paper: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractReferences", args={
            "paper": paper,
        }, mode="stream")
        return result
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))