###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Dict, List, Optional, TypeVar, Union, TypedDict, Type, Literal, cast
from typing_extensions import NotRequired
import pprint

import baml_py
from pydantic import BaseModel, ValidationError, create_model

from . import partial_types, types
from .types import Checked, Check
from .type_builder import TypeBuilder
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


OutputType = TypeVar('OutputType')


# Define the TypedDict with optional parameters having default values
class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]

class BamlAsyncClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __stream_client: "BamlStreamClient"

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__stream_client = BamlStreamClient(self.__runtime, self.__ctx_manager)

    @property
    def stream(self):
      return self.__stream_client


    
    async def ExtractNewPaperContent(
        self,
        previous_section: str,references: str,page_content: List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.NewPage:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "ExtractNewPaperContent",
        {
          "previous_section": previous_section,"references": references,"page_content": page_content,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.NewPage, raw.cast_to(types, types))
    
    async def ExtractPaper(
        self,
        paper: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Paper:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "ExtractPaper",
        {
          "paper": paper,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.Paper, raw.cast_to(types, types))
    
    async def ExtractPaperContent(
        self,
        references: str,page_content: List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.Page:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "ExtractPaperContent",
        {
          "references": references,"page_content": page_content,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.Page, raw.cast_to(types, types))
    
    async def ExtractReferences(
        self,
        paper: List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.References:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "ExtractReferences",
        {
          "paper": paper,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.References, raw.cast_to(types, types))
    


class BamlStreamClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    def ExtractNewPaperContent(
        self,
        previous_section: str,references: str,page_content: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.NewPage, types.NewPage]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "ExtractNewPaperContent",
        {
          "previous_section": previous_section,
          "references": references,
          "page_content": page_content,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.NewPage, types.NewPage](
        raw,
        lambda x: cast(partial_types.NewPage, x.cast_to(types, partial_types)),
        lambda x: cast(types.NewPage, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractPaper(
        self,
        paper: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.Paper, types.Paper]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "ExtractPaper",
        {
          "paper": paper,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.Paper, types.Paper](
        raw,
        lambda x: cast(partial_types.Paper, x.cast_to(types, partial_types)),
        lambda x: cast(types.Paper, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractPaperContent(
        self,
        references: str,page_content: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.Page, types.Page]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "ExtractPaperContent",
        {
          "references": references,
          "page_content": page_content,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.Page, types.Page](
        raw,
        lambda x: cast(partial_types.Page, x.cast_to(types, partial_types)),
        lambda x: cast(types.Page, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractReferences(
        self,
        paper: List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.References, types.References]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "ExtractReferences",
        {
          "paper": paper,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.References, types.References](
        raw,
        lambda x: cast(partial_types.References, x.cast_to(types, partial_types)),
        lambda x: cast(types.References, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    

b = BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)

__all__ = ["b"]