# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractNewPaperContent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.NewPage:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractNewPaperContent", llm_response=llm_response, mode="request")
        return typing.cast(types.NewPage, result)

    def ExtractPaper(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Paper:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractPaper", llm_response=llm_response, mode="request")
        return typing.cast(types.Paper, result)

    def ExtractPaperContent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Page:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractPaperContent", llm_response=llm_response, mode="request")
        return typing.cast(types.Page, result)

    def ExtractReferences(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.References:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractReferences", llm_response=llm_response, mode="request")
        return typing.cast(types.References, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractNewPaperContent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.NewPage:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractNewPaperContent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.NewPage, result)

    def ExtractPaper(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Paper:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractPaper", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Paper, result)

    def ExtractPaperContent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Page:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractPaperContent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Page, result)

    def ExtractReferences(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.References:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractReferences", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.References, result)

    