# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (9)
# #########################################################################

class CitationObject(BaseModel):
    in_text: typing.Optional[str] = None
    complete_reference: typing.Optional[str] = None
    url: typing.Optional[str] = None

class NewCitationObject(BaseModel):
    in_text: typing.Optional[str] = None
    complete_reference: typing.Optional[str] = None

class NewPage(BaseModel):
    sections: typing.List["Section"]

class NewSection(BaseModel):
    title: typing.Optional[str] = None
    content: typing.Optional[str] = None
    references: typing.List["CitationObject"]
    is_finished: typing.Optional[bool] = None

class Page(BaseModel):
    sections: typing.List["Section"]

class Paper(BaseModel):
    author: typing.List[str]
    title: typing.Optional[str] = None
    year: typing.Optional[str] = None
    abstract: typing.Optional[str] = None

class ReferenceObject(BaseModel):
    text: typing.Optional[str] = None
    url: typing.Optional[str] = None

class References(BaseModel):
    references: typing.List["ReferenceObject"]

class Section(BaseModel):
    title: typing.Optional[str] = None
    content: typing.Optional[str] = None
    references: typing.List["CitationObject"]
    is_finished: typing.Optional[bool] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
