# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CitationObject": types.CitationObject,
    "stream_types.CitationObject": stream_types.CitationObject,

    "types.NewCitationObject": types.NewCitationObject,
    "stream_types.NewCitationObject": stream_types.NewCitationObject,

    "types.NewPage": types.NewPage,
    "stream_types.NewPage": stream_types.NewPage,

    "types.NewSection": types.NewSection,
    "stream_types.NewSection": stream_types.NewSection,

    "types.Page": types.Page,
    "stream_types.Page": stream_types.Page,

    "types.Paper": types.Paper,
    "stream_types.Paper": stream_types.Paper,

    "types.ReferenceObject": types.ReferenceObject,
    "stream_types.ReferenceObject": stream_types.ReferenceObject,

    "types.References": types.References,
    "stream_types.References": stream_types.References,

    "types.Section": types.Section,
    "stream_types.Section": stream_types.Section,


}